### PR TITLE
Fix permission denied in CI

### PR DESCRIPTION
**Pull request by reakaleek**
## Summary

https://github.com/elastic/synthetics-recorder/issues/338 Fix permission denied during junit test recording.

## Implementation details

The xml files generated by the junit test reporter were created in the docker container with the root user. Hence, Jenkins was not able to read the file to execute the junit function.

Reusing the `UID` and `GID` of Jenkins in the docker container resolves the issue.

Further, the `package-lock.json` was updated with the command `npm update` because of the following error (inspired by https://github.com/npm/cli/issues/3374#issuecomment-1188070482):

image

```
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')
```
> Source: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fsynthetics-recorder-mbp/detail/PR-339/4/pipeline/86

during `npm ci`. This behavior happend both on Jenkins and locally.

Running `npm clear cache --force` did not help.

## How to validate this change

No permission errors during the Jenkins build.

### CODE REVIEW

**Comment by reakaleek** [comment]
@kyungeunni The permission issue is fixed now. However, there is a failing test that seems to be unrelated or is caused by updating the `package-lock.json` file. (Please see https://github.com/elastic/synthetics-recorder/pull/339#issue-1509025790, why it was necessary).

Can you help me with that?

**Comment by reakaleek** [comment]
cc @vigneshshanmugam 

Maybe you can also help here. In the description you can find the reason why I updated package-lock.json.
The described behaviour happens also locally on the `main` branch. 

Please let me know if you have ideas on how to resolve this.

Thank you

**Comment by amannocci** [comment]
It seems to be related to a mismatch between the checksum of our playwright [fork](https://github.com/elastic/playwright/tree/1.27.1-recorder) and the package-lock one.
We could update the package lock with the correct checksums.

```suggestion
-      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA==",
+      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ==",
```
And
```suggestion
-      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA=="
+      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ=="
```

**Comment by reakaleek** [comment]
> It seems to be related to a mismatch between the checksum of our playwright [fork](https://github.com/elastic/playwright/tree/1.27.1-recorder) and the package-lock one. We could update the package lock with the correct checksums.
> 
> ```
> -      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA==",
> +      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ==",
> ```
> 
> And
> 
> ```
> -      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA=="
> +      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ=="
> ```

Wow. Thank you for the suggestion. Will try!

**Comment by reakaleek** [comment]
> It seems to be related to a mismatch between the checksum of our playwright [fork](https://github.com/elastic/playwright/tree/1.27.1-recorder) and the package-lock one. We could update the package lock with the correct checksums.
> 
> ```
> -      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA==",
> +      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ==",
> ```
> 
> And
> 
> ```
> -      "integrity": "sha512-IjIOxds3UktyNPK+0XroM3IFFs1Dh83eKpy41Y3ydrzxNOYRVkL19u2mOPq0lUIiyrlRyGCNZvURKf7P608ftA=="
> +      "integrity": "sha512-TTqrLaBlD2fFRrP2T5mfmpzyH9u4/GplhzvK4daHFlHldWGx7Rkkm9OFFele5BuZHKzAgFb0zPu4Xh6c5tAOXQ=="
> ```

Thank you for the suggestion! With the help of your comment I realized running `npm update playwright` is enough to get rid of: 

```
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')
```

However, there is still a failing test when running `.ci/scripts/run-test.sh`

**Comment by kyungeunni** [comment]
Hi @reakaleek, sorry for the late reply!

We do download the forked playwright's branch and there have been changes in that branch so thus the checksum has been changed. I should have updated the package-lock.json to the main branch first rather than including it in my branch, apologies.

I will take a look at the failing tests now.

**Comment by kyungeunni** [comment]
Hey @reakaleek,
It seems like it is the permission change that affects the result of the tests.

I've applied your change to my branch and failed as same as this branch:
https://apm-ci.elastic.co/job/apm-agent-rum/job/synthetics-recorder-mbp/job/PR-337/4/
When reverting it back, the tests run without an issue but fail due to the reported bug:
https://apm-ci.elastic.co/job/apm-agent-rum/job/synthetics-recorder-mbp/job/PR-337/5/

At first, I was digging in to find the issue in the code but not only it seemed like not worth that much effort, but also we've had a number of occasions we had problems with the current setup. So I've tried github actions where we can drop the docker and just run as we run tests on our local machine in the PR #341. I've left some details there. Let me know what you think, and if you agree, we can close this PR and moving forward.

**Comment by reakaleek** [comment]
> Hey @reakaleek, It seems like it is the permission change that affects the result of the tests.
> 
> I've applied your change to my branch and failed as same as this branch: https://apm-ci.elastic.co/job/apm-agent-rum/job/synthetics-recorder-mbp/job/PR-337/4/ When reverting it back, the tests run without an issue but fail due to the reported bug: https://apm-ci.elastic.co/job/apm-agent-rum/job/synthetics-recorder-mbp/job/PR-337/5/
> 
> At first, I was digging in to find the issue in the code but not only it seemed like not worth that much effort, but also we've had a number of occasions we had problems with the current setup. So I've tried github actions where we can drop the docker and just run as we run tests on our local machine in the PR #341. I've left some details there. Let me know what you think, and if you agree, we can close this PR and moving forward.

Sounds good, since we want to migrate to gh actions anyway!

**Pull request closed without merging**
